FROM --platform=linux/amd64 node:lts

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

ENV PORT=3000

RUN npm run build

RUN npm install -g serve

CMD ["serve", "-s", "build" , "-l", "3000"]

