name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image server
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${{ secrets.DOCKER_USERNAME }}/vir_server:latest \
            --push \
            "server"

      - name: Build and push Docker image Client
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${{ secrets.DOCKER_USERNAME }}/vir_client:latest \
            --push \
            "client"

      - name: Run levant commands
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip
          curl -L https://releases.hashicorp.com/levant/0.3.1/levant_0.3.1_linux_amd64.zip -o levant.zip
          unzip levant.zip -d /usr/local/bin
          export NOMAD_ADDR=http://35.237.251.213:4646/
          export NOMAD_TOKEN=70e169da-6b91-b3a1-0579-a433926e285c
          
          levant deploy -var GIT_SHA="${{ env.GIT_SHA }}" server/backend.nomad
          levant deploy -var GIT_SHA="${{ env.GIT_SHA }}" client/frontend.nomad